# fly.toml file generated for elixir-jp-calendar on 2022-02-02T21:17:48+09:00

app = "elixir-jp-calendar"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 4000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "300s" # allow some time for startup
    interval = "15s"
    restart_limit = 6
    timeout = "2s"